name: my_emo_health
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  fl_chart: ^0.65.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  glassmorphism: ^3.0.0
  stomp_dart_client: ^1.0.0
  dash_chat_2: ^0.0.18
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
